### ISSUE TITLE
fseek(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by CoalaJoe** [m2mtech/flysystem-stream-wrapper#10]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/5689499/172833807-7b0e5eb8-5f24-46c8-8c14-9a0231761f7f.png">

Currently on a migration and using this library. I need to fork it though and add the following line for it to work:

StreamWrapper::109
```
                if (is_resource($this->current->handle)) {
                    fseek($this->current->handle, $currentPosition);
                }
```

I don't know why this is needed there, but everything works fine afterwards. Maybe it is because the Stream is being rewinded after Flysystems `writeStream`.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/5689499/172834220-f68aeec5-d290-4be5-8ef1-f716545962f6.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/5689499/172834298-3807421a-3da8-4dbd-b723-d93d94d5cfe3.png">

They also check weather or not the resource is seekable. That might be the right check.

**Comment by m2mtech** [comment]
@CoalaJoe Thanks for your help, PR has been merged and released
