### ISSUE TITLE
is_readable is not working

### ISSUE THREAD

**Issue by CoalaJoe** [m2mtech/flysystem-stream-wrapper#13]
We try to send E-Mails with Symfony's Mailer over async Messenger component.

The App creates attachments and triggers the SendMailMessage. We use the flysystem-stream-wrapper to store those attachments on a secure S3 storage.

It fails with `Path [REDACTED] is not readable.` in DataPart.php (Symfony Mailer Component)
<img width="912" alt="image" src="https://user-images.githubusercontent.com/5689499/175929717-04dc74d8-b257-4e39-94b7-8bf57d7bb3b8.png">

Locally, it is somehow not a problem. So I thought it could have been something about the locking component, but changing the lock to in-memory and TTL to 1 second did not resolve the issue.

So, I did a lot of debugging and printing and here are the results:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/5689499/175930654-cc1a0fe9-b333-4a5f-ac15-5a7892508186.png">

```
{
  attachment: {0}
  fileInfo: {}
  fileName: "[REDACTED]"
  isFile: true
  isReadable: false
  path: "gcloud://"
  pathInfo: {}
  pathname: "gcloud://[REDACTED]"
  realPath: false
  stat: {
    0: 0
    1: 0
    10: 1656327883
    11: -1
    12: -1
    2: 33152
    3: 0
    4: 0
    5: 65534
    6: 0
    7: 36798
    8: 1656327883
    9: 1656327883
    atime: 1656327883
    blksize: -1
    blocks: -1
    ctime: 1656327883
    dev: 0
    gid: 65534
    ino: 0
    mode: 33152
    mtime: 1656327883
    nlink: 0
    rdev: 0
    size: 36798
    uid: 0
  }
}
```

It seems to fail at `is_readable`, which returns false. So I tried to check the mode using stat, as I figured out with a bit of php source code reading that it seems to use that.

Ignoring the is_readable, I tried to open the file to make sure the FlySystem is setup correctly:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/5689499/175930965-eb93125a-13f5-4a4e-9d39-bffdc3c7fb75.png">

And it actually works:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/5689499/175931155-166fbbdc-afe2-4e5f-ba05-46c2cba206f5.png">

So the bug would seem to be, that the StreamStatCommand is not setting the right mode?

**Comment by m2mtech** [comment]
The `mode` returned by `stat` is 33152 which translates to 0100600 meaning it is a file and it is readable by the user owning the file. `uid` is 0 which usually is `root` and `gid` is 65534? Both are set in 

https://github.com/m2mtech/flysystem-stream-wrapper/blob/d66c64a8236493d548ac8bf8f7f18efbcc951e6c/src/Flysystem/StreamCommand/StreamStatCommand.php#L93-L94

which means it gets them from the current file (StreamStatCommand.php not your file) - which is bad - and I am open for improvements ;)

Thus to debug if this is the problem, please set the owner (`uid` & `gid`) of your `StreamStatCommand.php` file to the user who is running the code.

**Comment by m2mtech** [comment]
Dear @CoalaJoe 

please try if the latest commit solves your problem out of the box.
If not, I added the possibility to change uid & gid manually:

```php
FlysystemStreamWrapper::register('fly', $filesystem, [
    FlysystemStreamWrapper::UID => 1000,
    FlysystemStreamWrapper::GID => 1000,
]);
```

Put there the uid & gid of the user running your script.

If that also does not work, you can adjust the `PortableVisibilityConverter`, e.g.:

```php
FlysystemStreamWrapper::register('fly', $filesystem, [
    FlysystemStreamWrapper::VISIBILITY_FILE_PUBLIC => 0666,
    FlysystemStreamWrapper::VISIBILITY_FILE_PRIVATE => 0666,
    FlysystemStreamWrapper::VISIBILITY_DIRECTORY_PUBLIC => 0777,
    FlysystemStreamWrapper::VISIBILITY_DIRECTORY_PRIVATE => 0777,
    FlysystemStreamWrapper::VISIBILITY_DEFAULT_FOR_DIRECTORIES => Visibility::PUBLIC,
]);
```

**Comment by CoalaJoe** [comment]
Wow, thank you so much for the insight, fast response and solution.

I am adding this as a task on our side to check if this fixes the problem. 😄
