### ISSUE TITLE
visibility can still cause exceptions

### ISSUE THREAD

**Issue by jurriaanr** [m2mtech/flysystem-stream-wrapper#14]
To prevent the visibility problem there is a try catch around this operation

```
        try {
            $visibility = $current->filesystem->visibility($current->file);
        } catch (UnableToRetrieveMetadata $e) {
            if (!$current->ignoreVisibilityErrors()) {
                throw $e;
            }

            $visibility = Visibility::PUBLIC;
        }
```

in StreamStatCommand.php

However, if the adapter just returns the default flysytems' FileAttributes object, which sets visiblity to null (as f.e. [spaties dropboxadapter](https://github.com/spatie/flysystem-dropbox) does, a bug in Flysystem will give a TypeError since the visibility function should not return null but a string ([reported there](https://github.com/thephpleague/flysystem/issues/1531)). The TypeError is not caught by the above catch. It is probably a good idea to accept a wider range of throwables since any adapter may find their own way of letting know that visibility isn't a thing.

**Comment by m2mtech** [comment]
Wouldn't it be reasonable to fix faulty adapters?

Nevertheless, could you please provide a PR as I have no real test case to work against?

**Comment by jurriaanr** [comment]
I'm not sure if the adapter is at fault here, although they could probably help solving it as well. The return the FileAttributes object which is what is expected. It's really the FileSystem that should allow for the visibility to be null, because it makes sense for some random file system to have no concept of visibility, or it should default to public which is what your code does and makes sense as well. Anyhow, i made a PR

**Comment by m2mtech** [comment]
thanks for your help!
