### ISSUE TITLE
`is_writable` returns false for created directories

### ISSUE THREAD

**Issue by FelixZY** [m2mtech/flysystem-stream-wrapper#7]
I'm running into issues with the following code (minimal reproduction - my actual use case involves a third party lib)

```php
FlysystemStreamWrapper::register(
  "fly",
  new Filesystem(new LocalFilesystemAdapter("./")),
);
mkdir("fly://my-dir", 0666, true);
is_writable("fly://my-dir");
```

**Expected**
`is_writable` should return `true`

**Actual**
`is_writable` returns `false`

**Research**
When a new directory is created inside the `FlysystemStreamWrapper`, it seems as if permissions are set to `755`, meaning only the owner may write to the directory. Calling `fileowner("fly://my-dir")` returns `0` which is equivalent to the root user on my system - i.e. not my php user. This appears to cause php to believe it does not have write access to `"my-dir"`.

Forcing a write despite `is_writable` proves that the directory is, in fact, writable.

**Problems**
1. `FlysystemStreamWrapper` does not create directories with the requested access rights
2. Created directories erroneously report owner `0`

**Comment by m2mtech** [comment]
Can you please check, if the latest commit solves the problem?

**Comment by FelixZY** [comment]
@m2mtech Confirmed, things are working as expected using 3d4f65a. Thank you for the quick fix!

**Comment by FelixZY** [comment]
I took another look. Yes, the ownership and `is_writable` issues are resolved. However, despite calling `@mkdir('fly://', (int) 0666, true);` the created directory seems to have ownership `0755`.

**Comment by m2mtech** [comment]
That is a feature of Flysystem which only knows PUBLIC & PRIVATE which the local adapter by default translates to 0755 and 0700 for directories. You can adjust the values to your needs e.g.

```php
/** @see https://flysystem.thephpleague.com/docs/adapter/local/ */
$adapter = new LocalFilesystemAdapter(
    './',
    PortableVisibilityConverter::fromArray([
        'file' => [
            'public' => 0666,
            'private' => 0600,
        ],
        'dir' => [
            'public' => 0777,
            'private' => 0700,
        ],
    ])
);

**Comment by m2mtech** [comment]
@FelixZY Thank you very much for you detailed error description & research. I will close this issue with the release of the changes.

**Comment by FelixZY** [comment]
Ok, I will look further into that then. Thank you for your assistance!
